### ISSUE TITLE
Why don't load the minified version of ZeroClipboard?

### ISSUE THREAD

**Issue by javierbyte** [brigand/react-zeroclipboard#11]

**Comment by brigand** [comment]
Good idea, thanks.  Update to 0.4.1 ec60fcb5f81145c67104e179b0adc98358be712b, and when you do a production build you'll get the minified version.

```sh
# development
browserify myapp.js > bundle.js

# production
NODE_ENV=production browserify myapp.js > bundle.js
```

It's the same way you do a development/production build for react, so it should just work out of the box for most people.

**Comment by javierbyte** [comment]
Perfect! Thank you.
