### ISSUE TITLE
ZeroClipboard as a dependency instead of from a CDN?

### ISSUE THREAD

**Issue by tmcw** [brigand/react-zeroclipboard#12]
I'm interested in using this library on an application that will ideally only use a limited set of allowed CNAMEs for all resources. Would you accept a pull request that adds the ability to use a local copy of ZeroClipboard$ instead of loading it from a CDN?

**Comment by brigand** [comment]
See https://github.com/brigand/react-zeroclipboard/issues/4.  If global.ZeroClipboard exists at load time, it'll use that instead of fetching from the CDN.
