### ISSUE TITLE
Asynch?

### ISSUE THREAD

**Issue by winkler1** [brigand/react-zeroclipboard#14]
Hi-
 Was wondering if there's a way to do copy with a callback... I have text (json blob) generated by the server, is not precomputed. Did not see a way offhand.
Thanks,
Jeff

**Comment by brigand** [comment]
It's actually impossible, sadly.  It's a security restriction enforced in Flash 10+, similar to how window.open works in click handlers (needs to be synchronous in response to the event, or else it's blocked).

The best you can do is try to do it quickly before the user clicks it by detecting a nearby cursor or a hover event, and ask them to click again if they did it too quickly.
