### ISSUE TITLE
IE8 support?

### ISSUE THREAD

**Issue by jerrysu** [brigand/react-zeroclipboard#22]
ZeroClipboard stopped supporting IE8 sometime in 2.x (re: https://github.com/zeroclipboard/zeroclipboard#support). However, React does continue to support IE8 and `react-zeroclipboard` may be useful to anyone still supporting IE8.

I'm curious what your thoughts are on using an older version of ZeroClipboard from the CDN so that IE8 can be supported. Also, there is one line of code that needs to change in `loadScript.js` since `document.head` isn't supported in IE8: https://github.com/brigand/react-zeroclipboard/blob/master/loadScript.js#L37

**Comment by jerrysu** [comment]
Actually, after looking into it, it seems ZeroClipboard 2.0.2 doesn't even copy to clipboard anymore.

We'll probably just conditionally not load `react-zeroclipboard` in IE8 for now.

**Comment by brigand** [comment]
Could you try `npm install react-zeroclipboard@pre` on IE8? I haven't tested it on IE8 at all.

**Comment by jerrysu** [comment]
Hi @brigand, thanks for your quick response!

I gave `npm install react-zeroclipboard@pre` a try. With this version, there's no longer the JavaScript error about `document.head` in IE8. Copy to clipboard doesn't work, however.

I also test IE9 and Chrome. Those browsers are continuing to work fine.

**Comment by brigand** [comment]
Darn. I'll push this so it at least doesn't crash, but if you figure out something let me know.
