### ISSUE TITLE
Bad build dependencies

### ISSUE THREAD

**Issue by will-ob** [brigand/react-zeroclipboard#27]
Looks like new `react-dom` dependency should be in 'dependencies', not 'devDependencies'. Our build is breaking with missing package "react-dom". Backing up to 2.0.1 for now

https://github.com/brigand/react-zeroclipboard/commit/367d1f7e1b1ca98fc4e2428ee7650a61bf84707b

**Comment by brigand** [comment]
I don't like depending on specific versions of react in libraries. It just causes issues.

You should already have react-dom installed because you need ReactDOM.render to render things into the dom (React.render gives a deprecation warning).
