### ISSUE TITLE
semver problem in 2.0.2

### ISSUE THREAD

**Issue by javierbyte** [brigand/react-zeroclipboard#29]
the version 2.0.1 works fine with react 0.13, but the 2.0.2 doesn't.

Wouldn't it be better to add a new 2.0.3 version compatible the 2.0.1 (maybe the exact same code) so builds using `^2.0.0` won't break, and then create the version 2.1.0 to follow semver rules?

thanks.

**Comment by brigand** [comment]
Yeah, my bad. Pushed 2.0.3 which is the same as 2.0.1, and 3.0.0 which is the same as 2.0.2.
