### ISSUE TITLE
How to automatic copy the text?

### ISSUE THREAD

**Issue by dwqs** [brigand/react-zeroclipboard#30]
Hi, thanks a lot for this tool!

I used it in my project, code as follows:
```
<ReactZeroClipboard  text={"sssssss"}  onAfterCopy={this.handleCopy.bind(this)}
                                                   onErrorCopy={this.handleErrorCopy.bind(this)}>
        <span className="copy">Copy Link</span>
 </ReactZeroClipboard>
```

If I don't click the `span`, I can't copy the text. So how to automatic copy the text when the ReactZeroClipboard component is rendering(don't need to click the `span`)?

Thanks your res.

**Comment by brigand** [comment]
Due to security restrictions a click is required to copy text to the clipboard.
