### ISSUE TITLE
Not working, possibly issue with latest cdnjs version

### ISSUE THREAD

**Issue by benrlodge** [brigand/react-zeroclipboard#32]
Update - It seems to work fine on Google Canary - but I'm seeing this issue with latest Chrome, and Firefox.

You can see right on your demo page @brigand.

When you hover over the copy button:
`Uncaught Error: Error: An invalid exception was thrown.`

I haven't had a chance to dig in to it, but it looks like the issue may have something to do with loading the latest cdnjs version 2.2.0, as I have another app (using react-zerodclipboard v1.1.0) running in production that is loading 2.1.5 and it's working fine

Looks like there were some [zeroclipboard API](https://github.com/zeroclipboard/zeroclipboard/releases/tag/v2.2.0) changes that maybe are causing the issue?.

**Comment by evandavis** [comment]
Oddly enough, several of my coworkers are seeing this issue but I am _not_.

**Comment by brigand** [comment]
I tried changing it to 2.1.5 but it didn't fix the problem (chrome stable). I really don't know what to do here :/

**Comment by praveenaj** [comment]
I'm getting this issue too, on Chrome. Works fine in Firefox though

**Comment by DavidWells** [comment]
Samesies. Anyone find a fix?

**Comment by parterburn** [comment]
Example doesn't work in Chrome, either: http://brigand.github.io/react-zeroclipboard/

**Comment by brigand** [comment]
I tried the demo again and it's working for me now. It seems it's inconsistently working.

**Comment by hxgdzyuyi** [comment]
Example doesn't work in Chrome, either: http://brigand.github.io/react-zeroclipboard/


VM495:19 Uncaught Error: Error: An invalid exception was thrown.

**Comment by dsgn1graphics** [comment]
@brigand Take a look at my pull request https://github.com/brigand/react-zeroclipboard/pull/34. This fixed the issue for my company, I hope it helps.

**Comment by brigand** [comment]
Seems to be fixed by #34 if you pass the swfProp path with the location of the swf you want to use. For the docs we just downloaded it and hosted it with the other local assets.
