### ISSUE TITLE
swfPath and ZERO_CLIPBOARD_SOURCE via props

### ISSUE THREAD

**Issue by steplerbox** [brigand/react-zeroclipboard#33]
I need to pass swfPath and ZERO_CLIPBOARD_SOURCE like a props. I think, it would be nice.
Thanks.

**Comment by brigand** [comment]
Sorry for the late reply. Since you can load zeroclipboard yourself already, and these configs are global, it isn't important to have them be props.

You can now configure it by doing `ReactZeroClipboard.globalConfig.swfPath = '..'`. Published in v3.1.0.
