### ISSUE TITLE
Seems React.findDOMNode has been removed from latest React

### ISSUE THREAD

**Issue by alisman** [brigand/react-zeroclipboard#35]
Plugin fails because it relies on this method which has apparently been moved to ReactDOM

**Comment by brigand** [comment]
@alisman Do you have an error message or any extra information?

**Comment by alisman** [comment]
Using component I get error message "React.findDOMNode is not a function"

findDomNode function has been moved to ReactDOM in recent versions of React.

**Comment by brigand** [comment]
@alisman we use ReactDOM.findDOMNode. Can you take a screenshot of the stack trace?

**Comment by vshulev** [comment]
I'm also having the same problem:
![react-zeroclipboard](https://cloud.githubusercontent.com/assets/5750234/18609288/3a9e010a-7d07-11e6-8170-d9ca7c165534.PNG)

**Comment by brigand** [comment]
I have absolutely no idea. I did a `npm install react-zeroclipboard` and inspected the files. I went through history and we jumped directly from `this.getDOMNode()` to `ReactDOM.findDOMNode`. The code in componentDidMount is `var el = ReactDOM.findDOMNode(this);`.

**Comment by vshulev** [comment]
Found the issue - I didn't check what the latest version was and just blindly copied `npm install --save react-zeroclipboard@1` from the readme. I installed v3.2.1 just now and it's works with React v15 :+1: It may be worthwhile updating the readme to avoid this happening to other people in the future?

**Comment by brigand** [comment]
Putting the version in the readme seemed like a good idea at the time. Thanks for figuring this out.
