### ISSUE TITLE
Support to custom key combination(like ctrl+alt+c) or adding data to clipboard with custom menu link

### ISSUE THREAD

**Issue by piu** [brigand/react-zeroclipboard#39]
Hi,

I have question that does this module support custom key combination for copying to clipboard(like Ctrl+Alt+C)? Also if there is any support to copy to clipboard on click of any custom menu implementation like in any react function I want to copy some custom data to clipboard dynamically and later paste it on some other menu item (like paste to clipboard) click. 

Is there any example for it? I couldn't find anything of this sought

**Comment by brigand** [comment]
@piu I don't think zeroclipboard supports anything other than clicks due to security restrictions and interactions between web and flash.

For custom components, you need to wrap the element in the react-zeroclipboard component, which may or may not be possible with your components.
