### ISSUE TITLE
Fallback to global ZeroClipboard? 

### ISSUE THREAD

**Issue by justinbelcher** [brigand/react-zeroclipboard#4]
We've gotten bitten a few times by cdnjs being down (or a particular network blocking for one reason or another). It'd be nice to have a synchronous version that just uses an already global ZeroClipboard (although I understand the convenience of loading on-demand async).

**Comment by xgecko** [comment]
Why not just make zeroclipboard a requirement?

**Comment by brigand** [comment]
ZeroClipboard is the kind of thing that should always be loaded lazily. If anything I'd like to do a few checks to prevent loading it at all on browsers that don't support flash, and when the dom clipboard apis come out, I may change the implementation to prefer those over zeroclipboard, making the load less necessary.

But mostly it just makes using this library easier to use when you don't need to worry about the swf file being loaded correctly.
