### ISSUE TITLE
`process.nextTick` not available in browser environment

### ISSUE THREAD

**Issue by Shrugs** [brigand/react-zeroclipboard#40]
```
Uncaught TypeError: (intermediate value).nextTick is not a function
```
at https://github.com/brigand/react-zeroclipboard/blob/master/index.js#L148

Looks like this occurs on the second mounting of a ReactZeroClipboard component. If client exists, it seems to assume that it's being executed on the server (?)

**Comment by brigand** [comment]
Thanks! Published as 3.2.3.

**Comment by Shrugs** [comment]
Wow that was fast! Thank you!

**Comment by Shrugs** [comment]
Confirmed working 👍
