### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by davidhq** [brigand/react-zeroclipboard#6]
[Error] SyntaxError: Line 78: Unexpected token ) while parsing      /Users/david/Projects/meetcasts/node_modules/react-zeroclipboard/index.js while parsing file: /Users/david/Projects/meetcasts/node_modules/react-zeroclipboard/index.js
	global code (app.js, line 1)

**Comment by brigand** [comment]
Thanks, fixed in 0.2.1.
