### ISSUE TITLE
Detail `onCopy`, `onAfterCopy`, `onError` in Readme

### ISSUE THREAD

**Issue by chrisjhoughton** [brigand/react-zeroclipboard#8]
Great component - worked first time with zero pain. Nice one! 

It's fairly standard to want to change a button to "Copied" from "Copy to clipboard" after click. I noticed this is supported from looking in the source, would be good to put it in the main readme. 

Cheers!

**Comment by brigand** [comment]
Weird, it was on the site but not the readme.  Thanks, fixed.
